apiVersion: v1
kind: ConfigMap
metadata:
  name: grade-submission-api-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: grade-submission
    app.kubernetes.io/component: backend
data:
  {{- toYaml .Values.config | nindent 2 }}
