apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: grade-submission
spec:
  selector: # the pod to be selected
    app.kubernetes.io/instance: grade-submission-api # select the pod with the label app.kubernetes.io/instance=grade-submission-api
  ports:
    - port: 3000 # and port any traffic from 3000
      targetPort: 3000 # to the port 3000
