apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-secret
  namespace: grade-submission
type: Opaque
data:
  # The serialized form of the secret data is a base64 encoded string, representing the arbitrary (possibly non-string) data value here.
  MONGODB_USER: YWRtaW4=
  MONGODB_PASSWORD: cGFzc3dvcmQxMjM=
