apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - --providers.kubernetesingress
            - --entrypoints.web.address=:80
            - --api.dashboard=true
            - --api.insecure=true  # dashboard on :8080, dev only
            - --log.level=DEBUG
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
