apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: grade-submission
    app.kubernetes.io/component: database
type: Opaque
data:
  {{- toYaml .Values.secrets | nindent 2 }}
