apiVersion: apps/v1
kind: Deployment
metadata:
  # identifies the Deployment object
  name: grade-submission-api
  namespace: grade-submission
spec:
  # defines how the Deployment behaves
  replicas: 3 # number of pod copies to maintain
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50% # max unavailable pods
      maxSurge: 1 # The maximum number of pods that can be created over the desired number of pods.
  selector:
    # tells the Deployment which pods it owns
    matchLabels:
      app.kubernetes.io/instance: grade-submission-api # unique identifier — distinguishes this instance from other deployments of the same app
  template:
    # blueprint for the pods the Deployment creates (previously managed by grade-submission-api-pod.yaml)
    metadata:
      # labels attached to each created pod
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: grade-submission-api
    spec:
      # defines the containers running inside each pod
      containers:
        - name: grade-submission-api
          image: rslim087/kubernetes-course-grade-submission-api:stateless-v3
          # define healthchecks
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15 # to give the app time to start
            periodSeconds: 5 # how often to check
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 10 # to give the app time to start
            periodSeconds: 5 # how often to check
          env:
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: '27017' # ClusterIP service port
            - name: MONGODB_USER
              value: 'admin'
            - name: MONGODB_PASSWORD
              value: 'password123'
          resources:
            requests:
              memory: '48Mi'
              cpu: '70m'
            limits:
              memory: '96Mi'
          ports:
            - containerPort: 5001
