apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: grade-submission
spec:
  type: ClusterIP
  selector:
    # let's forward all traffic to the pod with following label
    app.kubernetes.io/instance: mongodb
  ports:
    - port: 27017
      targetPort: 27017
